# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1208, 819)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/main_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ContactTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ContactTabWidget.sizePolicy().hasHeightForWidth())
        self.ContactTabWidget.setSizePolicy(sizePolicy)
        self.ContactTabWidget.setAcceptDrops(False)
        self.ContactTabWidget.setDocumentMode(False)
        self.ContactTabWidget.setMovable(True)
        self.ContactTabWidget.setTabBarAutoHide(False)
        self.ContactTabWidget.setObjectName("ContactTabWidget")
        self.SearchTab = QtWidgets.QWidget()
        self.SearchTab.setObjectName("SearchTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SearchTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SearchContactButton = QtWidgets.QPushButton(self.SearchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchContactButton.sizePolicy().hasHeightForWidth())
        self.SearchContactButton.setSizePolicy(sizePolicy)
        self.SearchContactButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/search categories.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchContactButton.setIcon(icon1)
        self.SearchContactButton.setObjectName("SearchContactButton")
        self.horizontalLayout_4.addWidget(self.SearchContactButton)
        self.SearchContactBar = QtWidgets.QLineEdit(self.SearchTab)
        self.SearchContactBar.setClearButtonEnabled(True)
        self.SearchContactBar.setObjectName("SearchContactBar")
        self.horizontalLayout_4.addWidget(self.SearchContactBar)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.SearchContactList = QtWidgets.QListWidget(self.SearchTab)
        self.SearchContactList.setObjectName("SearchContactList")
        self.verticalLayout_3.addWidget(self.SearchContactList)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ContactTabWidget.addTab(self.SearchTab, icon2, "")
        self.friendTab = QtWidgets.QWidget()
        self.friendTab.setObjectName("friendTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.friendTab)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FriendTree = QtWidgets.QTreeWidget(self.friendTab)
        self.FriendTree.setMinimumSize(QtCore.QSize(0, 0))
        self.FriendTree.setAcceptDrops(False)
        self.FriendTree.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.FriendTree.setObjectName("FriendTree")
        self.verticalLayout_2.addWidget(self.FriendTree)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/contact.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ContactTabWidget.addTab(self.friendTab, icon3, "")
        self.groupTab = QtWidgets.QWidget()
        self.groupTab.setObjectName("groupTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.GroupTree = QtWidgets.QTreeWidget(self.groupTab)
        self.GroupTree.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.GroupTree.setObjectName("GroupTree")
        self.verticalLayout_4.addWidget(self.GroupTree)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/group.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ContactTabWidget.addTab(self.groupTab, icon4, "")
        self.horizontalLayout_2.addWidget(self.ContactTabWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ChatTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.ChatTabWidget.setTabsClosable(True)
        self.ChatTabWidget.setTabBarAutoHide(False)
        self.ChatTabWidget.setObjectName("ChatTabWidget")
        self.tab_0 = QtWidgets.QWidget()
        self.tab_0.setObjectName("tab_0")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.StatusListWidget = QtWidgets.QListWidget(self.tab_0)
        self.StatusListWidget.setObjectName("StatusListWidget")
        self.verticalLayout_5.addWidget(self.StatusListWidget)
        self.ChatTabWidget.addTab(self.tab_0, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.MessageListWidget = QtWidgets.QListWidget(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MessageListWidget.sizePolicy().hasHeightForWidth())
        self.MessageListWidget.setSizePolicy(sizePolicy)
        self.MessageListWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.MessageListWidget.setObjectName("MessageListWidget")
        self.verticalLayout_6.addWidget(self.MessageListWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.InputBox = QtWidgets.QTextEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputBox.sizePolicy().hasHeightForWidth())
        self.InputBox.setSizePolicy(sizePolicy)
        self.InputBox.setMinimumSize(QtCore.QSize(0, 0))
        self.InputBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.InputBox.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.InputBox.setObjectName("InputBox")
        self.horizontalLayout.addWidget(self.InputBox)
        self.SendButton = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton.sizePolicy().hasHeightForWidth())
        self.SendButton.setSizePolicy(sizePolicy)
        self.SendButton.setMinimumSize(QtCore.QSize(0, 0))
        self.SendButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.SendButton.setObjectName("SendButton")
        self.horizontalLayout.addWidget(self.SendButton)
        self.horizontalLayout.setStretch(0, 9)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.ChatTabWidget.addTab(self.tab_1, "")
        self.verticalLayout.addWidget(self.ChatTabWidget)
        self.verticalLayout.setStretch(0, 19)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1208, 30))
        self.menubar.setObjectName("menubar")
        self.MenuWebQQ_Python = QtWidgets.QMenu(self.menubar)
        self.MenuWebQQ_Python.setObjectName("MenuWebQQ_Python")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.MenuWebQQ_Python.menuAction())

        self.retranslateUi(MainWindow)
        self.ContactTabWidget.setCurrentIndex(2)
        self.ChatTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WebQQ-Python"))
        self.SearchContactBar.setPlaceholderText(_translate("MainWindow", "搜索联系人"))
        self.ContactTabWidget.setTabText(self.ContactTabWidget.indexOf(self.SearchTab), _translate("MainWindow", "Search"))
        self.FriendTree.headerItem().setText(0, _translate("MainWindow", "好友"))
        self.ContactTabWidget.setTabText(self.ContactTabWidget.indexOf(self.friendTab), _translate("MainWindow", "联系人"))
        self.GroupTree.headerItem().setText(0, _translate("MainWindow", "群组"))
        self.ContactTabWidget.setTabText(self.ContactTabWidget.indexOf(self.groupTab), _translate("MainWindow", "群组"))
        self.ChatTabWidget.setTabText(self.ChatTabWidget.indexOf(self.tab_0), _translate("MainWindow", "Status"))
        self.InputBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>输入</p></body></html>"))
        self.SendButton.setText(_translate("MainWindow", "发送"))
        self.ChatTabWidget.setTabText(self.ChatTabWidget.indexOf(self.tab_1), _translate("MainWindow", "Tab 1"))
        self.MenuWebQQ_Python.setTitle(_translate("MainWindow", "WebQQ-&Python"))

